---
title: "Survival Analysis of Mycardial Infarction"
author: "Davat, Claire; Fondzewong Wiyfengla, Anslem; Wieber, Andrew"
date: "July 20th, 2024"
output:
  pdf_document: default
  html_document: default
---

# Activate the libraries and import the dataset

```{r}
# purge stored data
rm(list=ls())
# in package timereg
library(survival)
library(timereg)
library(caret)
data(TRACE)
dim(TRACE) #Check the number of lines and rows
head(TRACE) #Look at the first data
```
# Count the number of unique patients and missing data
```{r}
#Find the number of unique patients
nbPatients <- length(unique(rownames(TRACE)))
paste("Number of unique patients =", nbPatients)

#Find the number of NA entries
paste("Total nb of NA =", sum(is.na(TRACE)))
```

# Cross-tabulation tables
```{r}
temp <- xtabs(~sex + status, data=TRACE)
rownames(temp) = c("Male","Female")
colnames(temp) = c("Alive", "Other", "Other", "Dead")
names(dimnames(temp)) <- c("SEX","DEATH STATUS (COUNTS)")
temp

cat("\n")

temp <- xtabs(~sex + chf, data=TRACE)
rownames(temp) = c("Male","Female")
colnames(temp) = c("Absent", "Present")
names(dimnames(temp)) <- c("SEX","CLINICAL HEART FAILURE (FRACTION)")
round(temp/sum(temp), 2)

cat("\n")

temp <- xtabs(~sex + diabetes, data=TRACE)
rownames(temp) = c("Male","Female")
colnames(temp) = c("Absent", "Present")
names(dimnames(temp)) <- c("SEX","DIABETES (FRACTION)")
round(temp/sum(temp), 2)

cat("\n")

temp <- xtabs(~sex + vf, data=TRACE)
rownames(temp) = c("Male","Female")
colnames(temp) = c("Absent", "Present")
names(dimnames(temp)) <- c("SEX","VENTRICULAR FIBRILLATION (FRACTION)")
round(temp/sum(temp), 2)
```

#Take a look at the age distribution
```{r}
hist(TRACE$age)
```

# Cox Proportional Hazard
```{r}
cox_model_interactions <- coxph(Surv(time, status == 9) ~ wmi*chf + wmi*age + wmi*sex + wmi*diabetes + wmi*vf +
                                  chf*age + chf*sex + chf*diabetes + chf*vf +
                                  age*sex + age*diabetes + age*vf +
                                  sex*diabetes + sex*vf +
                                  diabetes*vf,
                                data = TRACE)
summary(cox_model_interactions)
```

# Cox Proportional Hazard with Ridge Penalization 
```{r}
fit.coxph <- coxph(Surv(time, status == 9) ~ ridge(age + sex + wmi + diabetes + vf + chf), data=TRACE)
summary(fit.coxph)
```

# Cross-validation with K-Folds
```{r}
k = 10 #number of folds
folds <- createFolds(TRACE$status, k = k) 
  
# Loop through the folds 
for (i in 1:k){
  # Split into train and test 
  train <- TRACE[-folds[[i]],] 
  test <- TRACE[folds[[i]],] 
  # Train the model
  fit <- coxph(Surv(time, status == 9) ~ age + sex + wmi + diabetes + vf + chf, data=train)
}
```
```{r}
fit
```

